<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\source\CapFrameX.Data.Session\CapFrameX.Data.Session.csproj" />
    <ProjectReference Include="..\..\source\CapFrameX.Statistics.NetStandard\CapFrameX.Statistics.NetStandard.csproj" />
  </ItemGroup>
</Project>
